default: &default
  reap_stalled_role_runs:
    class: ReapStalledRoleRunsJob
    queue: default
    schedule: every minute
  scan_role_heartbeats:
    class: RoleHeartbeatScannerJob
    queue: default
    schedule: every 15 minutes
  scan_recurrent_tasks:
    class: RecurrentTaskScannerJob
    queue: default
    schedule: every hour

development:
  <<: *default

production:
  <<: *default
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
