Rails.application.routes.draw do
  # Authentication (generated by Rails 8 auth generator)
  resource :session
  resources :passwords, param: :token

  # User registration (sign-up)
  resource :registration, only: [ :new, :create ]

  # Account settings
  resource :settings, only: [ :show, :update ]

  # Projects
  resources :projects, only: [ :index, :new, :create, :edit, :update ] do
    resource :switch, only: [ :create ], module: :projects, controller: "switches"
    member do
      post :emergency_stop
    end
  end

  # Invitations (scoped to active project via Current.project)
  resources :invitations, only: [ :index, :new, :create ]

  # Invitation acceptance (public, token-based)
  resources :invitation_acceptances, only: [ :show, :update ], param: :token

  # Role Categories (scoped to active project via Current.project)
  resources :role_categories

  # Org Chart & Roles (scoped to active project via Current.project)
  resources :roles do
    resources :role_skills, only: [ :create, :destroy ]
    resources :heartbeats, only: [ :index ]
    resources :role_hooks
    resources :role_runs, only: [ :index, :show ] do
      member do
        post :cancel
      end
    end
    member do
      post :run
      post :pause
      post :resume
      post :terminate
      post :approve
      post :reject
      post :hire, to: "role_hirings#create"
    end
  end
  resource :org_chart, only: [ :show ]

  # Role Templates (browse and apply department templates)
  resources :role_templates, only: [ :index, :show ] do
    member do
      post :apply
    end
  end

  # Skills (scoped to active project via Current.project)
  resources :skills do
    resources :skill_documents, only: [ :create, :destroy ]
  end

  # Documents (scoped to active project via Current.project)
  resources :documents
  resources :document_tags, only: [ :index, :create, :destroy ]

  # Tasks (scoped to active project via Current.project)
  resources :tasks do
    resources :task_documents, only: [ :create, :destroy ]
    resources :messages, only: [ :create ]
    resource :approval, only: [ :update ], controller: "tasks/approvals"
    resource :rejection, only: [ :update ], controller: "tasks/rejections"
    member do
      post :delegate, to: "task_delegations#create"
      post :escalate, to: "task_escalations#create"
      post :ask_question, to: "task_questions#create"
    end
  end

  # Goals (scoped to active project via Current.project)
  resources :goals

  # Notifications (scoped to active project via Current.project)
  resources :notifications, only: [ :index ] do
    member do
      patch :mark_read
    end
    collection do
      post :mark_all_read
    end
  end

  # Audit Log (scoped to active project via Current.project)
  resources :audit_logs, only: [ :index ]

  # Config Versions (version history and rollback for Role)
  resources :config_versions, only: [ :index, :show ] do
    member do
      post :rollback
    end
  end

  # Dashboard (project command center — root landing page)
  resource :dashboard, only: [ :show ], controller: "dashboard" do
    scope module: :dashboards do
      resources :tasks, only: [ :index ]
      resources :activities, only: [ :index ]
      resources :approvals, only: [ :index ]
    end
  end

  # Health check - used by load balancers and uptime monitors
  get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"
end
