Rails.application.routes.draw do
  # Authentication (generated by Rails 8 auth generator)
  resource :session
  resources :passwords, param: :token

  # User registration (sign-up)
  resource :registration, only: [ :new, :create ]

  # Account settings
  resource :settings, only: [ :show, :update ]

  # Companies
  resources :companies, only: [ :index, :new, :create ] do
    resource :switch, only: [ :create ], module: :companies, controller: "switches"
  end

  # Invitations (scoped to active company via Current.company)
  resources :invitations, only: [ :index, :new, :create ]

  # Invitation acceptance (public, token-based)
  resources :invitation_acceptances, only: [ :show, :update ], param: :token

  # Org Chart & Roles (scoped to active company via Current.company)
  resources :roles
  resource :org_chart, only: [ :show ]

  # Agents (scoped to active company via Current.company)
  resources :agents do
    resources :capabilities, only: [ :create, :destroy ], controller: "agent_capabilities"
  end

  # Health check - used by load balancers and uptime monitors
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root "home#show"
end
